// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt1aoHQh5Mll81Z2WTTVWXPkk9GQ-J2hg',
    appId: '1:207721000238:web:ff0499ee886fc305935ebf',
    messagingSenderId: '207721000238',
    projectId: 'wisheyy',
    authDomain: 'wisheyy.firebaseapp.com',
    storageBucket: 'wisheyy.firebasestorage.app',
    measurementId: 'G-W5LX0VL4W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsM9fc0lPremq8oEC6rjQL6h6AHQJ-qaA',
    appId: '1:207721000238:android:1e7e7fd6b9e95302935ebf',
    messagingSenderId: '207721000238',
    projectId: 'wisheyy',
    storageBucket: 'wisheyy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8XUWLxLERMxkEwv3X7qRSi14YFDmKHjE',
    appId: '1:207721000238:ios:7ea5a00dad94060d935ebf',
    messagingSenderId: '207721000238',
    projectId: 'wisheyy',
    storageBucket: 'wisheyy.firebasestorage.app',
    iosBundleId: 'com.example.wisheyy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8XUWLxLERMxkEwv3X7qRSi14YFDmKHjE',
    appId: '1:207721000238:ios:7ea5a00dad94060d935ebf',
    messagingSenderId: '207721000238',
    projectId: 'wisheyy',
    storageBucket: 'wisheyy.firebasestorage.app',
    iosBundleId: 'com.example.wisheyy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt1aoHQh5Mll81Z2WTTVWXPkk9GQ-J2hg',
    appId: '1:207721000238:web:fa0d3876ea79f5df935ebf',
    messagingSenderId: '207721000238',
    projectId: 'wisheyy',
    authDomain: 'wisheyy.firebaseapp.com',
    storageBucket: 'wisheyy.firebasestorage.app',
    measurementId: 'G-GJL4G61PQ6',
  );
}
